trigger:
  branches:
    include:
    - main

variables:
  libraryCounter: 'ColorWheelCoreNet_$(Davisol.3rdParty.ColorWheelCoreNetMajorMinorVersion)'
  libraryBuildRevision: $[counter(variables['libraryCounter'], 11)]
  libraryBuildVersion: '$(Davisol.3rdParty.ColorWheelCoreNetMajorMinorVersion).$(libraryBuildRevision)'

name: 'ColorWheel_Core_Net_v$(Davisol.3rdParty.ColorWheelCoreNetMajorMinorVersion).$(libraryBuildRevision)$(Rev:.r)'

resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: DAVISOL agent job - Build and deploy ColorWheel.Core.Net
  pool:
    name: DAVISOL Pipelines
    demands:
    - msbuild
  steps:
  - checkout: self
  - task: DownloadSecureFile@1
    name: snkFile
    displayName: Download secure file
    inputs:
      secureFile: b8a2e8f1-b598-4cb4-be12-ac73524065d8
      retryCount: 5
  - task: NuGetToolInstaller@1
    displayName: Use NuGet 6.7.0
    inputs:
      versionSpec: 6.7.0
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      feedRestore: 3a11d72e-ad5c-4c0a-bff7-5237610444a0
  - task: Assembly-Info-NetCore@2
    displayName: Set Assembly Manifest Data
    inputs:
      InsertAttributes: true
      GeneratePackageOnBuild: true
      PackageId: ColorWheel.Core.Net
      VersionNumber: $(libraryBuildVersion)
      FileVersionNumber: $(libraryBuildVersion)
      InformationalVersion: $(libraryBuildVersion)
      PackageVersion: $(libraryBuildVersion)
  - task: MSBuild@1
    displayName: Build solution **/*.sln
    inputs:
      solution: '**/*.sln'
      msbuildVersion: '17.0'
      msbuildArchitecture: 'x64'
      platform: 'Any CPU'
      configuration: 'Release'
      msbuildArguments: '/p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(snkFile.secureFilePath)'
      clean: true
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)\lib\net6.0'
    inputs:
      SourceFolder: ColorWheel.Core.Net.Windows/bin/Release
      Contents: '**/ColorWheel.Core.*'
      TargetFolder: $(Build.ArtifactStagingDirectory)\lib\net6.0
      CleanTargetFolder: true
      OverWrite: true
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ColorWheel.Core.Net'
    inputs:
      ArtifactName: ColorWheel_Core_Net
  - task: NuGetCommand@2
    displayName: NuGet pack
    inputs:
      command: pack
      searchPatternPack: ColorWheel.Core.Net.Windows/ColorWheelNetWindows_Package.nuspec
      versioningScheme: byBuildNumber
      includeSymbols: true
      basePath: ColorWheel.Core.Net.Windows
  - task: NuGetCommand@2
    displayName: NuGet push
    inputs:
      command: push
      feedPublish: 3a11d72e-ad5c-4c0a-bff7-5237610444a0
      allowPackageConflicts: true
...
